baseurl = "http://geneandmelina.com"
title = "Gene & Melina"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Gene & Melina"
  description = 'Tying the knot'
  logo = "fa-diamond"
  copyright = "Gene & Melina"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "28.07.2018"
